version: "3.8"
services:
  ima:
    container_name: ima
    image: ${IMAGE}
    restart: always
    environment:
      DB_HOST: pg
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    networks:
      - dc-net

networks:
  dc-net:
    external: true