version: "3.8"
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
  ima:
    container_name: ima
    build: .
    env_file:
      - .env.local
    restart: always
    environment:
      DB_HOST: pg
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: 1234
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - dc-net

networks:
  dc-net:
    external: true

volumes:
  db_data: