spring:
  application:
    name: ima
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    password: ${DB_PASSWORD}
    username: postgres
    hikari:
      schema: ima
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000
ima:
