spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: logotipishe@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: ima
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    password: ${DB_PASSWORD}
    username: postgres
    hikari:
      schema: ima
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000
ima:
  mail-verification: false