spring:
  application:
    name: ima
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    password: ${DB_PASSWORD}
    username: postgres
    hikari:
      schema: ima
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret-key: 3cfa76ef14937c1d0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
ima:
